services:
  - type: web
    name: telegram-modbot
    runtime: python
    plan: free
    buildCommand: pip install -r telegram-bot/requirements.txt
    startCommand: python telegram-bot/main.py
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
